// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd5G3vzCAQhO8nN7GWlEIkaKrnUptxuDE',
    appId: '1:318316028823:web:32c79de81080a30d319ad2',
    messagingSenderId: '318316028823',
    projectId: 'ilussia-tarots',
    authDomain: 'ilussia-tarots.firebaseapp.com',
    storageBucket: 'ilussia-tarots.firebasestorage.app',
    measurementId: 'G-1204DERETV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVVU_2jHw0b4sBeLSehNvZ8ezwfkBBWF4',
    appId: '1:318316028823:android:ef15d50a1e23c53d319ad2',
    messagingSenderId: '318316028823',
    projectId: 'ilussia-tarots',
    storageBucket: 'ilussia-tarots.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCZlqwbdH-UFYoaCWCJdMZJOlopBT8_WA',
    appId: '1:318316028823:ios:37d723b9042a4c10319ad2',
    messagingSenderId: '318316028823',
    projectId: 'ilussia-tarots',
    storageBucket: 'ilussia-tarots.firebasestorage.app',
    androidClientId: '318316028823-kc9hunk00lee2ce2grfoitquetjaga5t.apps.googleusercontent.com',
    iosClientId: '318316028823-hcq8ggub8hnn23akbd39n9uqlbh9kaas.apps.googleusercontent.com',
    iosBundleId: 'com.example.ilussiaTarot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCZlqwbdH-UFYoaCWCJdMZJOlopBT8_WA',
    appId: '1:318316028823:ios:37d723b9042a4c10319ad2',
    messagingSenderId: '318316028823',
    projectId: 'ilussia-tarots',
    storageBucket: 'ilussia-tarots.firebasestorage.app',
    androidClientId: '318316028823-kc9hunk00lee2ce2grfoitquetjaga5t.apps.googleusercontent.com',
    iosClientId: '318316028823-hcq8ggub8hnn23akbd39n9uqlbh9kaas.apps.googleusercontent.com',
    iosBundleId: 'com.example.ilussiaTarot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd5G3vzCAQhO8nN7GWlEIkaKrnUptxuDE',
    appId: '1:318316028823:web:a8204161a07880d6319ad2',
    messagingSenderId: '318316028823',
    projectId: 'ilussia-tarots',
    authDomain: 'ilussia-tarots.firebaseapp.com',
    storageBucket: 'ilussia-tarots.firebasestorage.app',
    measurementId: 'G-4ZESHVJ3WX',
  );

}